IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TblBlasting' AND COLUMN_NAME = 'Remarks' AND TABLE_SCHEMA = 'Trans')
BEGIN
    ALTER TABLE [Trans].[TblBlasting] ADD [Remarks] NVARCHAR(MAX) NULL;
END
GO
