-- Check TblBDSEntry Schema and Data
SELECT TOP 5 * FROM [Trans].[TblBDSEntry];
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TblBDSEntry' AND TABLE_SCHEMA = 'Trans';

-- Check tblUser_New Schema
SELECT TOP 1 * FROM [dbo].[tblUser_New];
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblUser_New';
