-- Find correct SME table
SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '%SME%';

-- Check BDS Entry columns to confirm 'PartyId' exists
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TblBDSEntry' AND TABLE_SCHEMA = 'Trans';
