export const TRANSACTION_CONFIG = {
    'loading-from-mines': {
        apiEndpoint: '/api/transaction/loading-from-mines',
        table: '[Trans].[TblLoading]',
        idField: 'SlNo',
        defaultSort: 'LoadingDate',
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 80, frozen: true },
            { accessor: 'LoadingDate', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'ShiftInCharge', label: 'Shift In Charge', width: 200, frozen: true },
            { accessor: 'ManPower', label: 'Man Power', type: 'number', width: 100 },
            { accessor: 'RelayName', label: 'Relay', width: 150 },
            { accessor: 'SourceName', label: 'Source', width: 150 },
            { accessor: 'DestinationName', label: 'Destination', width: 150 },
            { accessor: 'MaterialName', label: 'Material', width: 150 },
            { accessor: 'HaulerName', label: 'Hauler', width: 150 },
            { accessor: 'LoadingMachineName', label: 'Loading Machine', width: 150 },
            { accessor: 'NoofTrip', label: 'No of Trip', type: 'number', width: 100 },
            { accessor: 'QtyTrip', label: 'Mgmt Qty/Trip', type: 'number', width: 120 },
            { accessor: 'NtpcQtyTrip', label: 'NTPC Qty/Trip', type: 'number', width: 120 },
            { accessor: 'TotalQty', label: 'Mgmt Total Qty', type: 'number', width: 150 },
            { accessor: 'TotalNtpcQty', label: 'NTPC Total Qty', type: 'number', width: 150 },
            { accessor: 'UnitName', label: 'Unit', width: 100 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
        ]
    },
    'internal-transfer': {
        apiEndpoint: '/api/transaction/internal-transfer',
        table: '[Trans].[TblInternalTransfer]',
        idField: 'SlNo',
        defaultSort: 'TransferDate',
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 80, frozen: true },
            { accessor: 'LoadingDate', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'ShiftInCharge', label: 'Shift In Charge', width: 200, frozen: true },
            { accessor: 'ManPower', label: 'Man Power', type: 'number', width: 100 },
            { accessor: 'RelayName', label: 'Relay', width: 150 },
            { accessor: 'SourceName', label: 'Source', width: 150 },
            { accessor: 'DestinationName', label: 'Destination', width: 150 },
            { accessor: 'MaterialName', label: 'Material', width: 150 },
            { accessor: 'HaulerName', label: 'Hauler', width: 150 },
            { accessor: 'LoadingMachineName', label: 'Loading Machine', width: 150 },
            { accessor: 'NoofTrip', label: 'Trips', type: 'number', width: 100 },
            { accessor: 'QtyTrip', label: 'Qty/Trip', type: 'number', width: 120 },
            { accessor: 'TotalQty', label: 'Total Qty', type: 'number', width: 150 },
            { accessor: 'UnitName', label: 'Unit', width: 100 },
            { accessor: 'Remarks', label: 'Remarks', width: 150 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
        ]
    },
    'material-rehandling': {
        apiEndpoint: '/api/transaction/material-rehandling',
        table: '[Trans].[TblMaterialRehandling]',
        idField: 'SlNo',
        defaultSort: 'RehandlingDate', // Configurable (Assumption: RehandlingDate?)
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 80, frozen: true },
            { accessor: 'RehandlingDate', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'ShiftInCharge', label: 'Shift In Charge', width: 200, frozen: true },
            { accessor: 'ManPower', label: 'Man Power', type: 'number', width: 100 },
            { accessor: 'RelayName', label: 'Relay', width: 150 },
            { accessor: 'SourceName', label: 'Source', width: 150 },
            { accessor: 'DestinationName', label: 'Destination', width: 150 },
            { accessor: 'MaterialName', label: 'Material', width: 150 },
            { accessor: 'HaulerName', label: 'Hauler', width: 150 },
            { accessor: 'LoadingMachineName', label: 'Loading Machine', width: 150 },
            { accessor: 'NoofTrip', label: 'No of Trip', type: 'number', width: 100 },
            { accessor: 'QtyTrip', label: 'Mgmt Qty/Trip', type: 'number', width: 120 },
            { accessor: 'NtpcQtyTrip', label: 'NTPC Qty/Trip', type: 'number', width: 120 },
            { accessor: 'TotalQty', label: 'Mgmt Total Qty', type: 'number', width: 150 },
            { accessor: 'TotalNtpcQty', label: 'NTPC Total Qty', type: 'number', width: 150 },
            { accessor: 'UnitName', label: 'Unit', width: 100 },
            { accessor: 'Remarks', label: 'Remarks', width: 150 }, // Added Remarks
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
        ]
    },
    'equipment-reading': {
        apiEndpoint: '/api/transaction/equipment-reading',
        table: '[Trans].[TblEquipmentReading]',
        idField: 'SlNo',
        defaultSort: 'Date',
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 70, frozen: true },
            { accessor: 'Date', label: 'Date', type: 'date', width: 110, frozen: true },
            { accessor: 'ShiftDisplay', label: 'Shift', width: 180, frozen: true },
            { accessor: 'ShiftInCharge', label: 'Shift Incharge', width: 220, frozen: true },
            { accessor: 'RelayName', label: 'Relay', width: 120 },
            { accessor: 'ActivityName', label: 'Activity', width: 150 },
            { accessor: 'EquipmentName', label: 'Equipment', width: 180 },
            { accessor: 'OperatorName', label: 'Operator/Driver', width: 220 },
            { accessor: 'OHMR', label: 'OHMR', type: 'number', width: 100 },
            { accessor: 'CHMR', label: 'CHMR', type: 'number', width: 100 },
            { accessor: 'NetHMR', label: 'Net HMR', type: 'number', width: 100 },
            { accessor: 'OKMR', label: 'OKMR', type: 'number', width: 100 },
            { accessor: 'CKMR', label: 'CKMR', type: 'number', width: 100 },
            { accessor: 'NetKMR', label: 'Net KMR', type: 'number', width: 100 },
            { accessor: 'DevelopmentHrMining', label: 'Dev. Hr (Mining)', type: 'number', width: 140 },
            { accessor: 'FaceMarchingHr', label: 'Face Marching Hr', type: 'number', width: 140 },
            { accessor: 'DevelopmentHrNonMining', label: 'Dev. Hr (Non Mining)', type: 'number', width: 160 },
            { accessor: 'BlastingMarchingHr', label: 'Blas. Marching Hr', type: 'number', width: 150 },
            { accessor: 'RunningBDMaintenanceHr', label: 'Run BD/Maint Hr', type: 'number', width: 150 },
            { accessor: 'TotalWorkingHr', label: 'Total Work Hr', type: 'number', width: 130 },
            { accessor: 'BDHr', label: 'BD Hr', type: 'number', width: 100 },
            { accessor: 'MaintenanceHr', label: 'Maint Hr', type: 'number', width: 100 },
            { accessor: 'IdleHr', label: 'Idle Hr', type: 'number', width: 100 },
            { accessor: 'SectorName', label: 'Sector', width: 120 },
            { accessor: 'PatchName', label: 'Patch', width: 150 },
            { accessor: 'MethodName', label: 'Method', width: 150 },
            { accessor: 'Remarks', label: 'Remarks', width: 200 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
        ]
    }
};
