export const TRANSACTION_CONFIG = {
    'drilling': {
        apiEndpoint: '/api/transaction/drilling',
        table: '[Trans].[TblDrilling]',
        idField: 'SlNo',
        defaultSort: 'DateOfDrilling',
        columns: [
            { accessor: 'SlNo', label: 'Sl.No', width: 80, frozen: true },
            { accessor: 'DateOfDrilling', label: 'Date of Drilling', type: 'date', width: 120, frozen: true },
            { accessor: 'DateOfBlasting', label: 'Date of Blasting', type: 'date', width: 120, frozen: true },
            { accessor: 'DrillingPatchId', label: 'Drilling Patch ID', width: 150, frozen: true },
            { accessor: 'DrillingAgency', label: 'Drilling Agency', width: 150 },
            { accessor: 'Equipment', label: 'Equipment', width: 150 },
            { accessor: 'Material', label: 'Material', width: 150 },
            { accessor: 'Location', label: 'Location', width: 150 },
            { accessor: 'Sector', label: 'Sector', width: 150 },
            { accessor: 'Scale', label: 'Scale', width: 100 },
            { accessor: 'Strata', label: 'Strata', width: 100 },
            { accessor: 'DepthSlab', label: 'Depth Slab', width: 120 },
            { accessor: 'NoofHoles', label: 'No of Holes', type: 'number', width: 100 },
            { accessor: 'TotalMeters', label: 'Total Meters', type: 'number', width: 100 },
            { accessor: 'Spacing', label: 'Spacing', type: 'number', width: 100 },
            { accessor: 'Burden', label: 'Burden', type: 'number', width: 100 },
            { accessor: 'TopRLBottomRL', label: 'Top RL Bottom RL', width: 150 },
            { accessor: 'AverageDepth', label: 'Average Depth', type: 'number', width: 120 },
            { accessor: 'Output', label: 'Output', type: 'number', width: 100 },
            { accessor: 'Unit', label: 'Unit', width: 80 },
            { accessor: 'TotalQty', label: 'Total Qty', type: 'number', width: 100 },
            { accessor: 'DrillingRemarks', label: 'Drilling Remarks', width: 200 },
            { accessor: 'Remarks', label: 'Remarks', width: 200 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created DateTime', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated DateTime', type: 'datetime', width: 180, disableFilter: true },
        ]
    },
    'loading-from-mines': {
        apiEndpoint: '/api/transaction/loading-from-mines',
        table: '[Trans].[TblLoading]',
        idField: 'SlNo',
        defaultSort: 'LoadingDate',
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 80, frozen: true },
            { accessor: 'LoadingDate', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'ShiftInchargeName', label: 'Incharge (Large-Scale)', width: 180, frozen: true },
            { accessor: 'MidScaleInchargeName', label: 'Incharge (Mid-Scale)', width: 180, frozen: true },
            { accessor: 'ManPower', label: 'Man Power', type: 'number', width: 100 },
            { accessor: 'RelayName', label: 'Relay', width: 150 },
            { accessor: 'SourceName', label: 'Source', width: 150 },
            { accessor: 'DestinationName', label: 'Destination', width: 150 },
            { accessor: 'MaterialName', label: 'Material', width: 150 },
            { accessor: 'HaulerName', label: 'Hauler', width: 150 },
            { accessor: 'LoadingMachineName', label: 'Loading Machine', width: 150 },
            { accessor: 'NoofTrip', label: 'No of Trip', type: 'number', width: 100 },
            { accessor: 'QtyTrip', label: 'Management Load Factor', type: 'number', width: 120 },
            { accessor: 'NtpcQtyTrip', label: 'NTPC Load Factor', type: 'number', width: 120 },
            { accessor: 'TotalQty', label: 'Mgmt Total Qty', type: 'number', width: 150 },
            { accessor: 'TotalNtpcQty', label: 'NTPC Total Qty', type: 'number', width: 150 },
            { accessor: 'UnitName', label: 'Unit', width: 100 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
        ]
    },
    'internal-transfer': {
        apiEndpoint: '/api/transaction/internal-transfer',
        table: '[Trans].[TblInternalTransfer]',
        idField: 'SlNo',
        defaultSort: 'TransferDate',
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 80, frozen: true },
            { accessor: 'LoadingDate', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'ShiftInCharge', label: 'Shift In Charge', width: 200, frozen: true },
            { accessor: 'ManPower', label: 'Man Power', type: 'number', width: 100 },
            { accessor: 'RelayName', label: 'Relay', width: 150 },
            { accessor: 'SourceName', label: 'Source', width: 150 },
            { accessor: 'DestinationName', label: 'Destination', width: 150 },
            { accessor: 'MaterialName', label: 'Material', width: 150 },
            { accessor: 'HaulerName', label: 'Hauler', width: 150 },
            { accessor: 'LoadingMachineName', label: 'Loading Machine', width: 150 },
            { accessor: 'NoofTrip', label: 'Trips', type: 'number', width: 100 },
            { accessor: 'QtyTrip', label: 'Qty/Trip', type: 'number', width: 120 },
            { accessor: 'TotalQty', label: 'Total Qty', type: 'number', width: 150 },
            { accessor: 'UnitName', label: 'Unit', width: 100 },
            { accessor: 'Remarks', label: 'Remarks', width: 150 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
        ]
    },
    'material-rehandling': {
        apiEndpoint: '/api/transaction/material-rehandling',
        table: '[Trans].[TblMaterialRehandling]',
        idField: 'SlNo',
        defaultSort: 'RehandlingDate', // Configurable (Assumption: RehandlingDate?)
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 80, frozen: true },
            { accessor: 'RehandlingDate', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'ShiftInchargeName', label: 'Incharge (Large-Scale)', width: 180, frozen: true },
            { accessor: 'MidScaleInchargeName', label: 'Incharge (Mid-Scale)', width: 180, frozen: true },
            { accessor: 'ManPower', label: 'Man Power', type: 'number', width: 100 },
            { accessor: 'RelayName', label: 'Relay', width: 150 },
            { accessor: 'SourceName', label: 'Source', width: 150 },
            { accessor: 'DestinationName', label: 'Destination', width: 150 },
            { accessor: 'MaterialName', label: 'Material', width: 150 },
            { accessor: 'HaulerName', label: 'Hauler', width: 150 },
            { accessor: 'LoadingMachineName', label: 'Loading Machine', width: 150 },
            { accessor: 'NoofTrip', label: 'No of Trip', type: 'number', width: 100 },
            { accessor: 'QtyTrip', label: 'Management Load Factor', type: 'number', width: 120 },
            { accessor: 'NtpcQtyTrip', label: 'NTPC Load Factor', type: 'number', width: 120 },
            { accessor: 'TotalQty', label: 'Mgmt Total Qty', type: 'number', width: 150 },
            { accessor: 'TotalNtpcQty', label: 'NTPC Total Qty', type: 'number', width: 150 },
            { accessor: 'UnitName', label: 'Unit', width: 100 },
            { accessor: 'Remarks', label: 'Remarks', width: 150 }, // Added Remarks
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
        ]
    },
    'equipment-reading': {
        apiEndpoint: '/api/transaction/equipment-reading',
        table: '[Trans].[TblEquipmentReading]',
        idField: 'SlNo',
        defaultSort: 'Date',
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 70, frozen: true },
            { accessor: 'Date', label: 'Date', type: 'date', width: 110, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 140, frozen: true },
            { accessor: 'ShiftInchargeName', label: 'Incharge (Large-Scale)', width: 180, frozen: true },
            { accessor: 'MidScaleInchargeName', label: 'Incharge (Mid-Scale)', width: 180, frozen: true },
            { accessor: 'RelayName', label: 'Relay', width: 120 },
            { accessor: 'ActivityName', label: 'Activity', width: 150 },
            { accessor: 'EquipmentName', label: 'Equipment', width: 180 },
            { accessor: 'OperatorName', label: 'Operator/Driver', width: 220 },
            { accessor: 'OHMR', label: 'OHMR', type: 'number', width: 100 },
            { accessor: 'CHMR', label: 'CHMR', type: 'number', width: 100 },
            { accessor: 'NetHMR', label: 'Net HMR', type: 'number', width: 100 },
            { accessor: 'OKMR', label: 'OKMR', type: 'number', width: 100 },
            { accessor: 'CKMR', label: 'CKMR', type: 'number', width: 100 },
            { accessor: 'NetKMR', label: 'Net KMR', type: 'number', width: 100 },
            { accessor: 'DevelopmentHrMining', label: 'Dev. Hr (Mining)', type: 'number', width: 140 },
            { accessor: 'FaceMarchingHr', label: 'Face Marching Hr', type: 'number', width: 140 },
            { accessor: 'DevelopmentHrNonMining', label: 'Dev. Hr (Non Mining)', type: 'number', width: 160 },
            { accessor: 'BlastingMarchingHr', label: 'Blas. Marching Hr', type: 'number', width: 150 },
            { accessor: 'RunningBDMaintenanceHr', label: 'Run BD/Maint Hr', type: 'number', width: 150 },
            { accessor: 'TotalWorkingHr', label: 'Total Work Hr', type: 'number', width: 130 },
            { accessor: 'BDHr', label: 'BD Hr', type: 'number', width: 100 },
            { accessor: 'MaintenanceHr', label: 'Maint Hr', type: 'number', width: 100 },
            { accessor: 'IdleHr', label: 'Idle Hr', type: 'number', width: 100 },
            { accessor: 'SectorName', label: 'Sector', width: 120 },
            { accessor: 'PatchName', label: 'Patch', width: 150 },
            { accessor: 'MethodName', label: 'Method', width: 150 },
            { accessor: 'Remarks', label: 'Remarks', width: 200 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
        ]
    },
    'blasting': {
        apiEndpoint: '/api/transaction/blasting/list', // Custom List Endpoint
        table: '[Trans].[TblBlasting]',
        idField: 'SlNo',
        defaultSort: 'Date',
        columns: [
            { accessor: 'SlNo', label: 'Sl.No', width: 80, frozen: true },
            { accessor: 'Date', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'BlastingPatchId', label: 'Blasting Patch ID', width: 150, frozen: true },
            { accessor: 'SMESupplierName', label: 'SME Supplier', width: 180 },
            { accessor: 'SMEQty', label: 'SME Qty. (Kg)', type: 'number', width: 140 },
            { accessor: 'MaxChargeHole', label: 'Max Charge/Hole (Kg)', type: 'number', width: 160 },
            { accessor: 'PPV', label: 'PPV (mm/sec.)', type: 'number', width: 140 },
            { accessor: 'NoofHolesDeckCharged', label: 'No Of Holes Deck Charged', type: 'number', width: 180 },
            { accessor: 'NoofWetHole', label: 'No Of Wet Hole', type: 'number', width: 140 },
            { accessor: 'AirPressure', label: 'Air Pressure (DB)', type: 'number', width: 140 },
            { accessor: 'TotalExplosiveUsed', label: 'Total Explosive Used (Kg)', type: 'number', width: 180 },
            { accessor: 'Remarks', label: 'Remarks', width: 200 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created DateTime', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated DateTime', type: 'datetime', width: 180, disableFilter: true },
        ],
        expandable: true,
        subTable: {
            title: 'Accessories Details',
            accessor: 'accessories',
            columns: [
                { accessor: 'SED', label: 'SED', align: 'right' },
                { accessor: 'TotalBoosterUsed', label: 'Booster Used', align: 'right' },
                { accessor: 'TotalNonelMeters', label: 'Nonel Meters', align: 'right' },
                { accessor: 'TotalTLDMeters', label: 'TLD Meters', align: 'right' }
            ]
        }
    },
    'electrical-entry': {
        table: '[Trans].[TblElectricalEntry]',
        idField: 'SlNo',
        apiPath: '/api/transaction/electrical-entry',
        columns: [
            { accessor: 'SlNo', label: '#', width: 50, frozen: true },
            { accessor: 'Date', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'RelayName', label: 'Relay', width: 150, frozen: true },
            { accessor: 'EquipmentName', label: 'Equipment/Plant', width: 180 },
            { accessor: 'OMR', label: 'OMR', type: 'number', width: 100 },
            { accessor: 'CMR', label: 'CMR', type: 'number', width: 100 },
            { accessor: 'TotalUnit', label: 'Total Unit', type: 'number', width: 120 },
            { accessor: 'UnitName', label: 'Unit', width: 100 },
            { accessor: 'Remarks', label: 'Remarks', width: 200 },
            { accessor: 'CreatedByName', label: 'Created By', width: 150 }, // Corrected Accessor if needed, checks View logic
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'Updated By', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true }
        ]
    },
    'crusher': {
        apiEndpoint: '/api/transaction/crusher/list',
        table: '[Trans].[TblCrusher]',
        idField: 'SlNo',
        defaultSort: 'Date',
        columns: [
            { accessor: 'SlNo', label: 'Sl.No', width: 80, frozen: true },
            { accessor: 'Date', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'ShiftInChargeName', label: 'Shift In Charge', width: 150, frozen: true },
            { accessor: 'ManPowerInShift', label: 'Manpower In Shift', type: 'number', width: 140 },
            { accessor: 'PlantName', label: 'Plant', width: 150 },
            { accessor: 'BeltScaleOHMR', label: 'OHMR (Belt Scale)', type: 'number', width: 150 },
            { accessor: 'BeltScaleCHMR', label: 'CHMR (Belt Scale)', type: 'number', width: 150 },
            { accessor: 'ProductionUnitName', label: 'Unit', width: 100 },
            { accessor: 'ProductionQty', label: 'Production Qty', type: 'number', width: 140 },
            { accessor: 'HaulerName', label: 'Hauler', width: 150 },
            { accessor: 'NoofTrip', label: 'Trip', type: 'number', width: 100 },
            { accessor: 'QtyTrip', label: 'Qty / Trip', type: 'number', width: 120 },
            { accessor: 'TripQtyUnitName', label: 'Unit', width: 100 },
            { accessor: 'TotalQty', label: 'Total Qty', type: 'number', width: 140 },
            { accessor: 'OHMR', label: 'OHMR', type: 'number', width: 120 },
            { accessor: 'CHMR', label: 'CHMR', type: 'number', width: 120 },
            { accessor: 'RunningHr', label: 'Running Hr', type: 'number', width: 120 },
            { accessor: 'KWH', label: 'KWH', type: 'number', width: 100 },
            { accessor: 'TotalStoppageHours', label: 'Total Stoppage Hours', type: 'number', width: 160 },
            { accessor: 'Remarks', label: 'Remarks', width: 200 },
            { accessor: 'CreatedByName', label: 'CreatedBy', width: 150 },
            { accessor: 'CreatedDate', label: 'Created DateTime', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedByName', label: 'UpdatedBy', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated DateTime', type: 'datetime', width: 180, disableFilter: true },
        ],
        expandable: true,
        subTable: {
            title: 'Stoppages',
            accessor: 'stoppages',
            columns: [
                { accessor: 'FromTime', label: 'From Time', type: 'time' },
                { accessor: 'ToTime', label: 'To Time', type: 'time' },
                { accessor: 'ReasonName', label: 'Reason' }, // Assuming API returns joined name
                { accessor: 'StoppageHours', label: 'Hours', align: 'right' },
                { accessor: 'Remarks', label: 'Remarks' }
            ]
        }
    },
    'water-tanker-entry': {
        apiEndpoint: '/api/transaction/water-tanker-entry',
        table: '[Transaction].[TblWaterTankerEntry]',
        idField: 'SlNo',
        defaultSort: 'EntryDate',
        columns: [
            { accessor: 'SlNo', label: 'SlNo', width: 80, frozen: true },
            { accessor: 'EntryDate', label: 'Date', type: 'date', width: 120, frozen: true },
            { accessor: 'ShiftName', label: 'Shift', width: 100, frozen: true },
            { accessor: 'DestinationName', label: 'Destination', width: 150 }, // Corrected Accessor
            { accessor: 'HaulerName', label: 'Hauler', width: 150 },
            { accessor: 'FillingPointName', label: 'Filling Pt', width: 150 },
            { accessor: 'NoOfTrip', label: 'Trips', type: 'number', width: 100 },
            { accessor: 'Capacity', label: 'Capacity', type: 'number', width: 100 },
            { accessor: 'TotalQty', label: 'Total Qty', type: 'number', width: 120 },
            { accessor: 'Remarks', label: 'Remarks', width: 200 },
            { accessor: 'CreatedBy', label: 'Created By', width: 150 },
            { accessor: 'CreatedDate', label: 'Created Date', type: 'datetime', width: 180, disableFilter: true },
            { accessor: 'UpdatedBy', label: 'Updated By', width: 150 },
            { accessor: 'UpdatedDate', label: 'Updated Date', type: 'datetime', width: 180, disableFilter: true },
        ]
    }
};
